version: '3.3'

services:

  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot
    depends_on:
      - db

  db:
    image: postgres:13.3
    restart: always
    volumes:
      - ./data/:/var/lib/postgresql/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    environment:
      - POSTGRES_PASSWORD=files123bot
      - POSTGRES_USER=files_bot
      - POSTGRES_DB=files_db
    ports:
      - 5432:5432

networks:
  tg_bot:
    driver: bridge
